name: Update Events

on:
  schedule:
    - cron: '0 15 * * *'  # 매일 00:00 KST = 15:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run fetch_events.py
        run: python scripts/fetch_events.py

      - name: Commit & Push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add events/events.json
          git commit -m "update events" || echo "No changes to commit"
          git push
